services:
  mongodb:
    image: mongo:latest
    container_name: local-mongodb
    ports:
      - "27017:27017"
    env_file:
      - ./.env.dev
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
